version: "3.3"

configs:
  dnsmasq-conf:
    file: ./dnsmasq/dnsmasq.conf
  pxelinux-menu:
    file: ./tftp-files/pxelinux.cfg/default

services:
  dns:
    image: jd-dnsmasq:latest
    build:
      context: ./dnsmasq
      dockerfile: dnsmasq.dockerfile
    cap_add:
    - "NET_ADMIN"
    network_mode: "host"
    entrypoint: ["dnsmasq", "-k", "--log-facility=-", "--conf-file=/dnsmasq.conf", "--user=root"]
    ports:
    - target: 69 #tftp
      published: 69
      protocol: udp
      mode: host
    - target: 67 #dhcp
      published: 67
      protocol: udp
      mode: host
    configs:
    - source: pxelinux-menu
      target: /tftp/bios/pxelinux.cfg/default
    - source: dnsmasq-conf
      target: /dnsmasq.conf
  http-kick:
    image: nginx:mainline-alpine
    ports:
    - target: 80
      published: 5123
      protocol: tcp
      mode: host
    volumes:
    - type: bind
      source: ./webroot
      target: /usr/share/nginx/html/kick
      read_only: true
    - type: bind
      source: /mnt/archiso
      target: /usr/share/nginx/html/archiso
      read_only: true
    - type: bind
      source: /mnt/centos
      target: /usr/share/nginx/html/centos
      read_only: true
#  deployo:
#    image: jd-deployo:latest
#    build:
#      context: ./deployo
#      dockerfile: flask.dockerfile
#    ports:
#    - target: 5000
#      published: 1337
#      protocol: tcp
#      mode: host
#    volumes:
#    - type: bind
#      source: ./tftp-files/pxelinux.cfg
#      target: /opt/pxelinux.cfg
#      read_only: false
#    - type: bind
#      source: ./tftp-files/machines
#      target: /opt/machines
#      read_only: false
