version: "3.7"

networks:
  mysql:
    driver: overlay
    attachable: true

volumes:
  sql_data1:
  sql_data2:
  sql_data3:

configs:
  my-cnf:
    file: ./my.cnf
  proxysql-cnf:
    file: ./proxysql.cnf
  proxysql-init:
    file: ./proxysql_user.sql

x-mysql: &sql_service
  image: mysql/mysql-server:5.7
  networks: [ "mysql" ]
  #    ports:
  #      - "3306:3306"
  environment:
    MYSQL_ROOT_HOST: '%'
    MYSQL_ROOT_PASSWORD: 'password'
    MYSQL_LOG_CONSOLE: 'true'
  configs:
    - source: proxysql-init
      target: /docker-entrypoint-initdb.d/00-proxysql-init.sql
  #      - source: my-cnf
  #        target: /etc/my.cnf
  deploy:
    mode: replicated
    replicas: 1
    placement:
      preferences:
        - spread: node.labels.sql == 1
        - spread: node.labels.sql

#
services:
  #docker run -d -v /path/to/proxysql.cnf:/etc/proxysql.cnf severalnines/proxysql
  proxysql:
    image: severalnines/proxysql
    networks: [ "mysql" ]
    ports:
      - "6032:6032"
      - "6033:6033"
      - "6080:6080"
    configs:
      - source: proxysql-cnf
        target: /etc/proxysql.cnf
    deploy:
      mode: replicated
      replicas: 1

  mysql1:
    <<: *sql_service
    volumes:
      - sql_data1:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        preferences:
          - spread: node.labels.sql == 1
          - spread: node.labels.sql

  mysql2:
    <<: *sql_service
    volumes:
      - sql_data2:/var/lib/mysql
    deploy:
      placement:
        preferences:
          - spread: node.labels.sql == 2
          - spread: node.labels.sql

  mysql3:
    <<: *sql_service
    volumes:
      - sql_data3:/var/lib/mysql
    deploy:
      placement:
        preferences:
          - spread: node.labels.sql == 3
          - spread: node.labels.sql

